### ISSUE TITLE
Multiple smaller bugs

### ISSUE THREAD

**Issue by AndErazor** [Shelkovenkov/defichain-income#1]
Hi defichain-income team,

first of all amazing job with the dashboard! While I use it daily I found some smaller bugs. Hope this is the intended way of reporting them:
- from time to time my balance is not displayed correctly. It seems the amount from my LM Pools is not included. Generally this works fine but sometimes it seems to be missing or evaluated with 0
- I am not able to re-set my staking balance to 0, I can adjust the value but it is not saving this change. When I open the page the next time it is back to the previous value
- Sometimes I am facing display errors with text not aligned with the graphic or headlines

Best regards
Andreas

**Comment by Shelkovenkov** [comment]
Hi,

first of all. Thank you for feedback. 

1. sometimes it can be because for all values we need response from the api, if it fails data are not correct.
2. Please if you update your addresses or stake amount klick on update button in settings. then it will be saved in the database.
3. Please upload screenshots so we can fix ist.

**Comment by Shelkovenkov** [comment]
@AndErazor do you have some issues? Otherwise will close here

**Comment by AndErazor** [comment]
Hi, sorry I forgot to response, Issue can be closed. Thanks.
